### ISSUE TITLE
Unable to create write data into bucket , not an app engine context 

### ISSUE THREAD

**Issue by Karthic-Hackintosh** [GoogleCloudPlatform/gcloud-golang#118]
Initially when tried running the storage app-engine example code i ran into this following issue which is being discussed in this stackoverflow thread http://stackoverflow.com/questions/29010718/google-cloud-storage-client-app-error-using-go-runtime-google-app-engine . 
The discussion enabled me to fix the issue with sample code  and get it compiled https://github.com/GoogleCloudPlatform/gcloud-golang/blob/master/examples/storage/appengine/app.go.

But now i have deployed this code on Go runtime on app engine , and i get this following error when i check it on the Log monitoring facility in the developers console **createFile: unable to write data to bucket "xxxx-87609.appspot.com", file "demo-testfile-go": Post https://www.googleapis.com/upload/storage/v1/b/xxxx-xxxx-87609.appspot.com/o?alt‌​=json&projection=full&uploadType=multipart: not an App Engine context** 

It would have been great if the example code would have run gracefully without the need to fix it . 
Here is how im initializing the context ( as suggested in the stackoverflow answer) 

    c := appengine.NewContext(r)
    hc := &http.Client{}
    ctx := cloud.NewContext(appengine.AppID(c), hc)
    hc.Transport = &oauth2.Transport{
        Source: google.AppEngineTokenSource(ctx, storage.ScopeFullControl),
        Base:   &urlfetch.Transport{Context: c},
    }
    ctx = cloud.NewContext(appengine.AppID(c), hc)
	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	fmt.Fprintf(w, "Demo GCS Application running from Version: %v\n", appengine.VersionID(c))
	fmt.Fprintf(w, "Using bucket name: %v\n\n", bucket)

	d := &demo{
		c:   c,
		w:   w,
		ctx: ctx,
	}

	n := "demo-testfile-go"
	d.createFile(n)
	d.readFile(n)

**Comment by gmlewis** [comment]
You've got some extra lines in there...  The following works for me:

```go
	c := appengine.NewContext(r)
	hc := &http.Client{
		Transport: &oauth2.Transport{
			Source: google.AppEngineTokenSource(c, storage.ScopeFullControl),
			Base:   &urlfetch.Transport{Context: c},
		},
	}
	ctx := cloud.NewContext(appengine.AppID(c), hc)
	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	fmt.Fprintf(w, "Demo GCS Application running from Version: %v\n", appengine.VersionID(c))
	fmt.Fprintf(w, "Using bucket name: %v\n\n", bucket)
	log.Infof(c, "Using bucket name: %v\n\n", bucket)

	d := &demo{
		c:   c,
		w:   w,
		ctx: ctx,
	}

	n := "demo-testfile-go"
	d.createFile(n)
	d.readFile(n)
	d.copyFile(n)
```

**Comment by Karthic-Hackintosh** [comment]
I had used the same piece of code before , i tried this again , it fails to compile with the following  error 
**cannot use c (type "appengine".Context) as type context.Context in function argument:
	"appengine".Context does not implement context.Context (missing Deadline method)**

**Comment by gmlewis** [comment]
Can you try updating your code with:
`go get -u google.golang.org/appengine`

**Comment by Karthic-Hackintosh** [comment]
yes , i updated it , and the issue still persists

**Comment by gmlewis** [comment]
Can you please email me the full output of "gcloud --verbosity debug preview app run ." ?  I would like to see the full error message.  Thanks!

**Comment by Karthic-Hackintosh** [comment]
yes , can i have your email address ? Thank You !

**Comment by gmlewis** [comment]
Yes, it is gmlewis at google dot com... I sent you an email to your yahoo address on your profile page.

**Comment by karalabe** [comment]
Just a random thought, is your Go version up to date? I remember seeing this error a while back and teh issue was that the Deadline was added in a later release of Go and appengine used an older one. (However, as far as I know appengine updated to 1.4, so that shouldn't be an issue). However it could be worthwhile to check.

**Comment by rakyll** [comment]
This is an oauth2 package bug, see https://github.com/golang/oauth2/issues/98.

**Comment by Karthic-Hackintosh** [comment]
@karalabe , I have latest version of both Go and AppEngine !
@rakyll , Do i have to wait till this bug is fixed to be able to write string data from my Go Runtime on App Engine directly into  a file in Google Cloud Storage ?? Is there any other way i could achieve the objective , this has become a issue to move ahead with further development of our application !

**Comment by karalabe** [comment]
I am running on GAE and GCE and am able to access GCS so either something broke since Fabruary when I pulled the update last time, or there's something wrong on your end. It all works perfectly fine for me.

**Comment by rakyll** [comment]
@Karthic-Hackintosh, please use the workaround suggested on the issue. Construct the context using the following helper function:

```
func cloudContext(aeCtx context.Context) (context.Context, error) {
        conf, err := google.JWTConfigFromJSON(json, storage.ScopeFullControl)
        if err != nil {
                return nil, err
        }
        client := conf.Client(aeCtx)
        client.Transport = &oauth2.Transport{
                Source: google.AppEngineTokenSource(aeCtx, storage.ScopeFullControl),
                Base:   &urlfetch.Transport{Context: aeCtx},
        }
        return cloud.NewContext(projectId, client), nil
}
```

**Comment by karalabe** [comment]
There was also my suggestion from a while back: I am running on top of this since then and I've never had issues. Has this been broken since?

https://github.com/GoogleCloudPlatform/gcloud-golang/issues/99

**Comment by defcronyke** [comment]
I am having the same issue "not an App Engine context". There are about three slightly different workarounds floating around on here and stackoverflow, I have tried them all and they all fail.

For example, the workaround two posts above doesn't work because we are trying to make a context.Context, so how can we pass one in to the helper function when we haven't been able to successfully make a context.Context yet? I have an appengine.Context, not a context.Context.

The workaround my gmlewis above doesn't work because it calls google.AppEngineTokenSource() with an appengine.Context, but apparently google.AppEngineTokenSource() takes a context.Context, so it doesn't compile.

The workaround posted here: http://stackoverflow.com/questions/29010718/google-cloud-storage-client-app-error-using-go-runtime-google-app-engine , fails with "Post ... not an App Engine context"

And yet some people are saying some of these work for them. How is this possible if it doesn't work for me?

FYI, I am trying to use Exchange() from "golang.org/x/oauth2" Go package, and since I need to pass it a context.Context, I am hitting this same bug.

**Comment by PSG-Luna** [comment]
You will need to change your app to use "google.golang.org/appengine"
instead of "appengine" as import path for any of these workarounds to work.
The new import path uses context.Context instead of appengine.Context and
has a few other API improvements, it will however take some effort to
convert.

**Comment by defcronyke** [comment]
Wow that is a big change! Where is the official announcement to make this import path change? I learned how to use these technologies from the official docs but I've never seen mention of this on there.

**Comment by gmlewis** [comment]
I apologize for the confusion.  I didn't realize the example still showed the original "appengine" import.  I'm working on updating it.

**Comment by Karthic-Hackintosh** [comment]
@gmlewis  The updated code sample is failing to run . I could see this following error in the Log monitoring facility of the App Engine Developers console  
**This request caused a new process to be started for your application, and thus caused your application code to be loaded for the first time. This request may thus take longer and use more CPU than a typical request for your application.
     Process terminated because the request deadline was exceeded. (Error code 123)**

**Comment by gmlewis** [comment]
The first thing to check is the App Engine logs to see if anything unusual happened.
The second thing to realize is that requests on the default module are limited to 60 seconds... so it is possible that you may not want to run the full demo.

Finally, if you just want to write a string into a file in GCS, then delete all the other processing done in the example and modify the "createFile" example to print your string into the object.

So, for example, you could change the "createFile" function to be something like this:
```go
// createFile creates a file in Google Cloud Storage.
func (d *demo) createFile(fileName, myString string) {
	fmt.Fprintf(d.w, "Creating file /%v/%v\n", bucket, fileName)

	wc := storage.NewWriter(d.ctx, bucket, fileName)
	wc.ContentType = "text/plain"
	if _, err := wc.Write([]byte(myString)); err != nil {
		d.errorf("createFile: unable to write data to bucket %q, file %q: %v", bucket, fileName, err)
		return
	}
	if err := wc.Close(); err != nil {
		d.errorf("createFile: unable to close bucket %q, file %q: %v", bucket, fileName, err)
		return
	}
}
```

I hope that helps.

**Comment by kraoadori** [comment]
I updated the code , this leaves me with new Error in Log 
***createFile: unable to close bucket "xxx.appspot.com", file "demo-testfile-go": googleapi: Error 404: Not Found, notFound***

**Comment by Karthic-Hackintosh** [comment]
I updated the code , this leaves me with new Error in Log 
***createFile: unable to close bucket "xxx.appspot.com", file "demo-testfile-go": googleapi: Error 404: Not Found, notFound***

This following messaged is displayed on the browser 
***
Demo GCS Application running from Version: 3.382942966319033211
Using bucket name: xxx.appspot.com

Creating file /xxx.appspot.com/demo-testfile-go

Demo failed

***

**Comment by gmlewis** [comment]
This failure is in production or running locally?
Please send me the full App Engine console log for that request via email.
Are you able to manually create a file in that bucket from the Developers Console?

**Comment by Karthic-Hackintosh** [comment]
Yes I'm manually able to create files on bucket..The failure is in production

**Comment by gmlewis** [comment]
I have not yet received the full App Engine console log via email for that request.
I have pushed the example to production and it works for me without modification.
Have you modified the example source code?
Please email me the App IP so I can investigate.

**Comment by Karthic-Hackintosh** [comment]
@gmlewis , I have just mailed you the log .

**Comment by Karthic-Hackintosh** [comment]
Firstly i thank @gmlewis for helping us out in fixing this . Here is what that had went wrong 
1.Had to Accept New Terms of Service at appengine.google.com . It would have been great if i would have been forcibly redirected to this page when i enabled the API's for the first time (because these terms are concerning the users of these API's )
![terms](https://cloud.githubusercontent.com/assets/2609511/6752353/c8bd0f72-cf33-11e4-883a-a3e1a53aa0b1.png)
2. On the settings of the same page i had to create the default bucket . The Go Runtime sample code writes data into the default bucket , so if the default bucket for any reason if not yet been created the write or any other operation from the sample code fails . I had to click to create button below the Cloud Integration Heading which is seen in the image below . 
![create](https://cloud.githubusercontent.com/assets/2609511/6752464/c7faaff8-cf34-11e4-9c96-849b43838dc0.png)

**Comment by nikolasborrel** [comment]
I’m as well trying to recover from a panic situation (running latest App Engine/Cloud/Go versions) .

@gmlewis states that "google.golang.org/appengine” should be imported now instead of “appengine”.

This is what happens when the new context command is triggered

c := appengine.NewContext(r)

[restful] recover from panic situation: - invalid context.Context type; it should be created with cloud.NewContext
   /tmp/appengine/go/src/runtime/asm_amd64.s:401
   /tmp/appengine/go/src/runtime/panic.go:387
   google.golang.org/cloud/internal/cloud.go:127
   google.golang.org/cloud/internal/cloud.go:118
   google.golang.org/cloud/storage/storage.go:274
   services/requests-notifications.go:225
   services/requests-notifications.go:158
   github.com/emicklei/go-restful/container.go:197
   github.com/emicklei/go-restful/container.go:76
   go/src/net/http/server.go:1265
   go/src/net/http/server.go:1541
   go/src/appengine_internal/api_prod.go:280
   go/src/appengine_internal/api_prod.go:214
   /tmp/appengine/go/src/runtime/asm_amd64.s:403
   /tmp/appengine/go/src/reflect/value.go:419
   /tmp/appengine/go/src/reflect/value.go:296
   _:427
   /tmp/appengine/go/src/runtime/asm_amd64.s:2246

I would like to do something as simple as fetching some data from the cloud storage in the App Engine environment as

c := appengine.NewContext(request.Request)
if rc, err = storage.NewReader(c, “my_bucket", “my_data"); err != nil {		
		log.Errorf(c, "%v", err)
		response.WriteError(ws.HTTPStatusCodeInternalServerError, errors.New(“failed reading from storage"))
		return
}

If I create a cloud instance as

func GetServiceAccountCredentials() *http.Client {
	conf := jwt.Config{
		Email:      “my_email@developer.gserviceaccount.com",
		PrivateKey: []byte("-----BEGIN RSA PRIVATE KEY——\nm_yprivate_key\n-----END RSA PRIVATE KEY-----\n"),
		Scopes:     []string{storage.ScopeFullControl},
		TokenURL:   google.JWTTokenURL,
	}
	return conf.Client(oauth2.NoContext)
}

client := ws.GetServiceAccountCredentials()
ctx := cloud.NewContext(ws.APP_ID, client)

then I get the error

"oauth2: cannot fetch token: Post https://accounts.google.com/o/oauth2/token: not an App Engine context”

I have tried to find a solution for several days, but no luck!

Can somebody tell me how to fetch cloud storage data from the App Engine environment (it works from my Google Compute instance)??

**Comment by gmlewis** [comment]
Can you please try out the information found here: https://github.com/golang/oauth2/#app-engine
and let me know how that works for you?

**Comment by gmlewis** [comment]
cloud.NewContext will ideally go away at some point.
You should use appengine.NewContext to get the baseline context, and pass that via cloud.WithContext to get a context that works for both App Engine APIs and Cloud APIs.

**Comment by nikolasborrel** [comment]
Good news! No panic in c := newappengine.NewContext(request.Request) anymore. Did you made some changes to the App Engine? Because that was my main problem!

And the following works as expected, thanks!

c := newappengine.NewContext(request.Request)
hc := &http.Client{
   Transport: &oauth2.Transport{
			Source: google.AppEngineTokenSource(c, storage.ScopeFullControl),
			Base:   &urlfetch.Transport{Context: c},
		},
}
ctx := cloud.WithContext(c, ws.APP_ID, hc)
if rc, err = storage.NewReader(ctx, "my_bucket", my_data"); err != nil {
  ...
}

**Comment by gmlewis** [comment]
Excellent.  Glad to hear it.  Many parts have been moving within the last couple of months, but maybe just updating everything did the trick?  I don't know.

**Comment by GoesToEleven** [comment]
On your imports ... you don't want this:

	"google.golang.org/appengine"
	"google.golang.org/cloud/datastore"

You want this:

	"google.golang.org/appengine"
	"google.golang.org/appengine/datastore"

**Comment by patrickToca** [comment]
Trying the demo "google.golang.org/cloud/examples/storage/appengine".
I receive the following message:
"2015/12/09 12:08:48 createFile: unable to write data to bucket "xxxxx.appspot.com", file "demo-testfile-go": Post https://www.googleap
is.com/upload/storage/v1/b/xxxxx.appspot.com/o?alt=json&projection=full&uploadType=multipart: not an App Engine context".

My code is:
imports:
         "golang.org/x/net/context"
	"golang.org/x/oauth2"
	"golang.org/x/oauth2/google"

	"appengine"
	newappengine "google.golang.org/appengine"
	newurlfetch "google.golang.org/appengine/urlfetch"
	"google.golang.org/appengine/file"
	"google.golang.org/cloud/storage"
	"google.golang.org/cloud"
in the handler:
	c := appengine.NewContext(r)
	ctx := newappengine.NewContext(r)
	hc := &http.Client{}
	hc.Transport = &oauth2.Transport{
		Source: google.AppEngineTokenSource(ctx, storage.ScopeFullControl),
		Base:   &newurlfetch.Transport{Context: ctx},
	}
	ctx = cloud.NewContext(appengine.AppID(c), hc)

What is not correct? Thanks. I am just trying to migrate from blobstore to gcstorage.

**Comment by ernestoalejo** [comment]
```go
  
  "golang.org/x/oauth2/google"
  "google.golang.org/appengine"
  "google.golang.org/cloud"
  "google.golang.org/cloud/storage"

  client, err := google.DefaultClient(ctx, storage.ScopeFullControl)
  if err != nil {
    return ....
  }

  ctx = cloud.WithContext(ctx, appengine.AppID(ctx), client)

  // Usage
  if err := storage.DeleteObject(ctx, bucket, filename); err != nil {
    ....
  }
```

**Comment by patrickToca** [comment]
@ernestoalejo Thanks. Is there a complete example that simply works (with useful comments 'how to')?

**Comment by ernestoalejo** [comment]
There is an example here, though it is not a walkthrough:
https://github.com/GoogleCloudPlatform/gcloud-golang/tree/master/examples

**Comment by patrickToca** [comment]
Hi Ernesto.

this is exactly the one I cannot run this morning.

I will start over tomorrow with clearer mind.

Thanks.

Patrick

On 09/12/2015 13:15, Ernesto Alejo wrote:
>
> There is an example here, though it is not a walkthrough:
> https://github.com/GoogleCloudPlatform/gcloud-golang/tree/master/examples
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/gcloud-golang/issues/118#issuecomment-163227421>.
>

--
