### ISSUE TITLE
ReadRows(...) only adapt one ReadOption

### ISSUE THREAD

**Issue by Natata** [GoogleCloudPlatform/gcloud-golang#143]
ReadRows accepts multiple ReadOption
```
func (t *Table) ReadRows(ctx context.Context, arg RowRange, f func(Row) bool, opts ...ReadOption)
```
but in the bigtable.go#L278 
https://github.com/GoogleCloudPlatform/gcloud-golang/blob/df65e0af2d15158fecd80eed6333e2927bf2ed54/bigtable/bigtable.go#L278

it would only adapt last one ReadOption as filter
```
func (rf rowFilter) set(req *btspb.ReadRowsRequest) { req.Filter = rf.f.proto() }
```

**Comment by dsymonds** [comment]
I'm not sure what the issue is. You're looking at code for one particular ReadOption implementation; any future ReadOption implementations will be responsible for doing their own work.

If you're trying to pass multiple filters to one ReadRows call, the answer is that you cannot do that. The underlying RPC only permits a single filter, so you'll need to combine your multiple filters by using, for instance, `bigtable.ChainFilters` or `bigtable.InterleaveFilters`.
