### ISSUE TITLE
bigtable: No such thing as a "prototype table" for search.go

### ISSUE THREAD

**Issue by hegemonic** [GoogleCloudPlatform/gcloud-golang#145]
The comments in `examples/bigtable/search/search.go` claim that there's a Cloud Bigtable "prototype table" called `shakespearetemplate`, which "is an existing table containing some documents." Of course, there's no such thing on Cloud Bigtable.

What's more, you can't rebuild the `docindex` table unless the `shakespearetemplate` table also exists in your cluster.

The concept of a pre-populated table appears to be a holdover from internal code. It should be removed from `search.go`.

**Comment by dsymonds** [comment]
The comment probably isn't clear enough, but the intention is that you *may* have an existing table containing documents and you can use the sample code to index those documents rather than have to upload them one at a time. That concept is definitely not a holdover from internal code, but perhaps is a distraction for the sample code.

@jcd2 wrote this sample; John, do you have an opinion here?
