### ISSUE TITLE
metadata.OnGCE is flaky

### ISSUE THREAD

**Issue by Carrotman42** [GoogleCloudPlatform/gcloud-golang#194]
The implementation of OnGCE does an http.Get to "http://metadata.google.internal" using a client that has timeouts set to 750ms. Sometimes (I can repro semi-consistently when running inside a docker container) the func returns false, presumably due to timing out.

OnGCE also caches its result, so there's no way to retry. A workaround is to invent my own OnGCE func with longer timeouts, but I'd like to avoid doing that in the long term.

**Comment by bradfitz** [comment]
I don't like any solution I can think of.

The answer certainly isn't raising the timeout. The timeout is already too high. It exists to not slow down non-GCE users who might have a blackholed route to that IP.

Retrying sucks. That implies it's possible for one call to OnGCE to say false and a subsequent call to return true. No program should have to think about such a case. And it's unacceptable to even allow programs to have to care about that case, since so few would do it correctly.

We could increase the timeout but make things nicer to non-GCE programs by racing any IP connect failure against a DNS lookup failure. But then we have to think about false negatives due to DNS config lookup problems.

Is this the GCE metadata server (which runs on the same physical machine) taking over 750 ms? I kinda doubt it. Is it the VM itself being overloaded? Perhaps we look at how long we've ran. But that's OS specific.

Also OS-specific is looking up our hypervisor's details from the kernel. We might be able to probe Linux enough to figure out whether we're on GCE, but I don't want to do that for N operating systems.

**Comment by Carrotman42** [comment]
Does the code actually need to verify that the header response contains "Metadata-Flavor: Google" to be correct? If not, can we just rely on DNS resolution on "metadata.google.internal"?

The VM is not overloaded and is an n1-standard-1. I'm not certain why the metadata server is being slow, but it definitely is: I'm seeing i/o timeouts on normal metadata Get requests as well.

**Comment by derekperkins** [comment]
I'm seeing > 10% of requests in a day timeout.

**Comment by derekperkins** [comment]
To be a littler clearer, it's using `github.com/golang/oauth/google.DefaultTokenSource` on a Managed VM that often times out for us, which is hitting the metadata server.

**Comment by piosz** [comment]
We are encountering the same issue in Kubernetes. See https://github.com/kubernetes/kubernetes/issues/22176

**Comment by piosz** [comment]
Thank you @bradfitz for fixing this. I'll try it.

cc @mwielgus
