### ISSUE TITLE
bigtable: Bigtable slow-down when using unlimited queries

### ISSUE THREAD

**Issue by akhenakh** [GoogleCloudPlatform/gcloud-golang#295]
When performing a query without `bigtable.LimitRows()` using the same predicate but counting/filtering the same number of rows, we are observing a slow-down of the response, it’s also impacting all the subsequent queries, (see gist https://gist.github.com/akhenakh/55eaeba80a5b167cdc12a09c413a3e80).

We first thought the client was flooded by the data stream, receiving a gigantic amount of data but the tested rows are very small (around 100 bytes) and a tcpdump shows only 1 megabyte of data transmitted between the server and the client for the whole test.

The gist reveals the problem with a small amount of queries, we are even more impacted by this problem in production where we may have dozens of queries running in parallel.

We tried to put some debugs in the cancel for loop: https://github.com/GoogleCloudPlatform/gcloud-golang/blob/master/bigtable/bigtable.go#L137

We are seeing it’s called one time only when using LimitRows() and around 5 times while not using it.

Note that we are using bigtable client at 4a23f97e60c9a14de1269e78812e59ca94033d85 for now.

**Comment by garye** [comment]
Thanks for the gist, I'll try to reproduce the behavior and get back to you.

**Comment by akhenakh** [comment]
UPDATE: Using updated repo as of 320877575d8d2d5cdb38e526184b8d04bc115946

The timing is more stable between limited queries and unlimited, it's not impacting the timing of subsequent queries anymore which is reassuring, but still terribly slow.
```
2016/07/21 17:49:48 limit  100001# 100 29.714272ms
2016/07/21 17:49:48 limit  100001# 100 5.004632ms
2016/07/21 17:49:48 limit  100001# 100 4.80384ms
2016/07/21 17:49:48 limit  100001# 100 6.180341ms
2016/07/21 17:49:48 limit  100001# 100 5.158882ms
2016/07/21 17:49:50 filter 100001# 100 222.885425ms
2016/07/21 17:49:50 filter 100001# 100 180.958129ms
2016/07/21 17:49:50 filter 100001# 100 192.427624ms
2016/07/21 17:49:50 filter 100001# 100 205.158643ms
2016/07/21 17:49:51 filter 100001# 100 271.996317ms
2016/07/21 17:49:53 limit  100001# 100 6.509047ms
2016/07/21 17:49:53 limit  100001# 100 6.082441ms
2016/07/21 17:49:53 limit  100001# 100 13.434973ms
2016/07/21 17:49:53 limit  100001# 100 7.865662ms
2016/07/21 17:49:53 limit  100001# 100 8.610329ms
2016/07/21 17:49:55 filter 100001# 100 226.394969ms
2016/07/21 17:49:55 filter 100001# 100 207.271761ms
2016/07/21 17:49:55 filter 100001# 100 219.394952ms
2016/07/21 17:49:56 filter 100001# 100 259.132954ms
2016/07/21 17:49:56 filter 100001# 100 221.69617ms
2016/07/21 17:49:56 filter 100001# 100 243.170191ms
2016/07/21 17:49:56 filter 100001# 100 325.008942ms
2016/07/21 17:49:57 filter 100001# 100 272.38434ms
2016/07/21 17:50:00 filter 100001# 100 3.383122152s
2016/07/21 17:50:00 filter 100001# 100 234.488626ms
2016/07/21 17:50:02 filter nothingHerePrefix 0 4.028662ms
2016/07/21 17:50:04 limit  nothingHerePrefix 0 3.994737ms
```

**Comment by garye** [comment]
Can you tell me a little bit about the data in the table? Number of rows, column families, etc.

**Comment by akhenakh** [comment]
As displayed by `cbt`
the key is a prefix `100001` + a reverse timestamp `2633311904000000000` + a random id `X57913060dd2678412eac3c3289ba9`

```
100001#2633311904000000000#X6791306edd2678412eac3c3289ba9
  rootposts:id                             @ 2016/07/21-16:28:16.000000
    "X6791306edd2678412eac3c3289ba9"
  rootposts:fullcell                       @ 2016/07/21-16:28:16.000000
    "1000000000000001"
  rootposts:latlng                         @ 2016/07/21-16:28:16.000000
    ""
```
very small amount of data
only one version for each cell
around 800k entries under the `100001#` prefix

**Comment by garye** [comment]
I'm glad the behavior is more stable in the newer version.

I believe the difference between your server-side filter and client-side predicate is expected behavior. When you use the predicate version of the query Bigtable will return way more than 100 rows, which takes time to read on the server, transfer over the network and deserialize on the client (I suspect this is the killer). If you can't express your filter in Bigtable's filter language then this is your only option, and you'll need to inspect every row on the client. If you can use a Bigtable filter then it will perform much better, as you demonstrated with this test.

What is your actual use case? Is there any reason not to use a limit filter instead of a client-side predicate?

**Comment by akhenakh** [comment]
I agree with your analysis but it does not match what we are observing especially the amount of  captured network data that went to the client is very low.

In the gist we are accepting the first hundred lexically ordered keys we are seeing, the filter is a basic yes.
The time to transfer over the network and deserialize the first hundred should be exactly the same as the limited version.

We have thousands of reverse timestamped entries we would grab the first 100 most recent that match a certain criteria in a cf.

But this is not even what we are doing in the gist, we are filtering but always accepting the first hundred the gap is 8ms to >200ms that sounds unreasonable.

**Comment by garye** [comment]
"The time to transfer over the network and deserialize the first hundred should be exactly the same as the limited version."

If I'm understanding this correctly then it's not actually the case. A single `ReadRowsResponse` comes back in both scenarios, but in the unfiltered version there are many more `Chunks` that come back in a single response. 

When I run your gist with a similar data set I see similar overall timings. I added logging in `bigtable.go`'s `ReadRows` method to see the size of the `ReadRowsResponse`, which can be obtained with `proto.Size(res)`. The unfiltered `ReadRowsResponse` is 1.8MB and contains > 10000 `Chunks`. Proto unmarshaling takes around 30ms and the rest of the time is waiting for that data to be returned from the server, which obviously includes both server-side processing time as well as data transmission. There is also a fair amount of time spent in GC which might be due to the protobuf library not being as efficient as possible.

That all generally meets my expectations. If you can figure out how to further limit the number of rows that get returned via a filter then that's probably going to be the biggest win.

**Comment by akhenakh** [comment]
Thanks for your research and explanations.
Did not know the first transmitted chunk would be that big, any way we could control that size?

It looks to me Bigtable API is exposing a stream but the first byte is 200ms away, I hardly see it as a normal behavior. 
Filtering server side is not always an option and accepting a >200ms latency is not an option either :/

I'll open a private ticket to the support, in the meantime can we keep this one open since recent work on the bigtable client is directly changing timing on this problem?

**Comment by garye** [comment]
Sure, keep this one open for now. We'll discuss internally to see if there is anything we can fix on our side or if there are better recommendations we can give you for making your use case perform better.

**Comment by garye** [comment]
I put together a gist that basically does paging using an offset and limit. Certainly faster if you only want to inspect a small number of records. I'm seeing 15ms to find 100 rows where it fetches 100 at a time and accepts a row with 1/3 probability. Let me know if this is helpful.

https://gist.github.com/garye/6ac56a6c770eacd5ae4226d6b2c214d6

**Comment by akhenakh** [comment]
Hi Gary,

Thanks for your answer, I'll experiment this idea into real code to see if it fits and let you know.

**Comment by garye** [comment]
Any updates, @akhenakh?

**Comment by akhenakh** [comment]
Hi Gary,

Your proposed cursor solution is working but is adding too much latencies for our needs.
We are investigating those latencies on a supported ticket.

At least the slowdowns observed before https://github.com/GoogleCloudPlatform/gcloud-golang/commit/320877575d8d2d5cdb38e526184b8d04bc115946 are not there anymore.
You can close this one.
Thank you.

**Comment by garye** [comment]
Thanks for the update. Let me know if I can help with the latency issues you're still facing.
