### ISSUE TITLE
appengine: limit outgoing connections [needs further investigation]

### ISSUE THREAD

**Issue by broady** [GoogleCloudPlatform/gcloud-golang#305]
App Engine flexible(?) can only support a limited number of outgoing connections.

**Comment by raggi** [comment]
cc @adamtanner

**Comment by bradfitz** [comment]
What's the limit?

What's this bug about, constraining some client library (which? all?) from hitting the max and getting errors?

**Comment by okdave** [comment]
@broady do you have more info? AFAICT, the number of open connections should be predictable for any given API (correct me if I'm wrong), so the developer should be able to control the concurrent requests/connections themselves…

**Comment by broady** [comment]
This came up during a customer meeting. I didn't quite understand the details.

If a system (e.g., App Engine) has a limit for outgoing connections, I don't think it's for libraries/packages like this one to limit their connections.

**Comment by okdave** [comment]
I agree. It seems the if the customer has a hard limit on connections, they should be able to achieve this themselves with their own `http.RoundTripper` implementation that they passing via `option.WithBaseHTTPClient` to the relevant APIs – @bradfitz correct me if I'm wrong and that wouldn't be feasible.

**Comment by okdave** [comment]
Closing for now. Please re-open if there's a compelling reason.

**Comment by raggi** [comment]
What they described was that during relatively heavy Datstore usage, they were seeing their processes hitting the fd limit. This was on MVM, so I presume it's at the userspace default of 1024.

We should ask them for a replication case, but their description of doing around 500 transactions per second should be sufficient to attempt a repetition.

I believe the desired behavior here would be to be able to set a limit that would lead to blocking, rather than having the system limit lead to errors.
