### ISSUE TITLE
logging/apiv2: move the auto generated package to an internal package

### ISSUE THREAD

**Issue by rakyll** [GoogleCloudPlatform/gcloud-golang#310]
Ideally, we don't want our users to be able to depend on apiv2 directly. It is auto-generated and doesn't have the same API compatibility promises we have for the rest of the cloud packages. We should move the generated package to an internal.

Thoughts?

/cc @okdave @jba

**Comment by bradfitz** [comment]
Hide all the things!

**Comment by rakyll** [comment]
apiv2 is not even imported by the logging package. I suppose its current location is used as a temporary location to publish the auto generated client. As far as I understand, keeping it out of internal packages is intentional.

Could we find a better spot for such clients who doesn't have a particular destination to be published from rather than polluting the cloud package namespace?

**Comment by jba** [comment]
> apiv2 is not even imported by the logging package

It is imported by the new logging package, in review at https://code-review.googlesource.com/#/c/5512/.

**Comment by jba** [comment]
We had extensive internal discussions about the right import paths for these packages. But I don't think we considered moving the generated clients used by veneers to internal. Offhand I think that makes sense. 

@jgeewax @anthmgoogle @saicheems @pongad @okdave @broady: What do you think about putting generated clients that are wrapped by a hand-written client in an internal directory? Internal directories are not accessible outside their parent, so only the hand-written client would be able to use the generated client.

There will be other generated clients that will not have a hand-written counterpart, and they will live in this repo under the path *api*/apiv*N*.

**Comment by broady** [comment]
We planned to publish auto-generated packages, for products that don't yet (or never will) have hand-written packages. For example, where would the auto-generated gRPC package for the App Engine API or Service Management API live?

Maybe the answer is another import path prefix, but I don't think "it isn't hand-written, so doesn't belong at `cloud.google.com/go/...`" is an argument enough.

Note: this issue tracker is public, please don't use internal names. It's confusing to users trying to follow along.

**Comment by rakyll** [comment]
I think the main argument is whether we can follow the conventions of the hand-written packages in auto-generated ones. If we can, the auto-generated clients will naturally look like they are a part of the broader cloud packages. If not, I am concerned that they will pollute and break the integrity.

> For example, where would the auto-generated gRPC package for the App Engine API or Service Management API live?

I was wondering about it. Why aren't they living under google.golang.org/api somewhere? Is the main concern the grouping of the Cloud APIs together under a package?

**Comment by pongad** [comment]
@jba Thank you for looping me in. I think internal directory is not the right choice for the reasons that @broady already pointed out. Another aspect to the argument is that **not** putting the autogenerated client into internal directory lets us change our minds later. If we publish a new client for a new service (let's call the service....`dowhatiwant`) under `dowhatiwant/apiv1` and we later want to publish a hand-written version, where does the autogenerated client go now? If we leave it at `dowhatiwant/apiv1`, it's inconsistent with putting logging under internal. But if we move it to internal, we break existing users.

> Is the main concern the grouping of the Cloud APIs together under a package?

I'm not sure if it's the "main concern", but I think it is valuable. Before someone can hand-write a `dowhatiwant` client, the autogenerated client is probably valuable enough to be put in a discoverable place. Am I making any sense?

**Comment by broady** [comment]
The `dowhatiwant` client would live at `cloud.google.com/go/dowhatiwant`. Anything with the `apiv` prefix stays auto-generated.

**Comment by jba** [comment]
@pongad makes a crucial point: we may later add a hand-written client on top of a generated one---in fact, that's likely to happen. I vote against making generated clients internal.

**Comment by okdave** [comment]
I think most of the original points of the discussion have been touched on:

- the cloud folk want all the cloud APIs gathered together in one place with "cloud" prominent in the name (hence the umbrella import of `cloud.google.com`)
- we will end up with a mix of autogen and handwritten APIs, and there will be (many?) cases where we start with the autogen before investing in a full handwritten version

I don't think it's bad to expose both versions, where they exist. My thought has always been that the handwritten copy would let users use 95% of the API in a really natural/beautiful/idiomatic way (for example: all CUJs should be achievable in the handwritten). There will exist 5% of use cases which fall outside that, and for which we should be happy for "power" users to use an autogen or gRPC package directly.

Once the autogen libraries have stabilised, I don't see any reason why the wouldn't have the same compatability promises. In fact, in many ways, the promise could be *stronger* since they are version via the import path.

There is an open question of "where do non-Cloud gRPC autogen libraries live?". I agree that somewhere like `google.golang.org/api` makes sense for that, though we'd have to resolve how they interact with the existing JSON-based clients there. It's also beyond the scope of this repo.

**Comment by rakyll** [comment]
> There is an open question of "where do non-Cloud gRPC autogen libraries live?".

I think the cloud umbrella works better if we want to encourage power users to fall back to the underlying APIs. It is more discoverable and we may have a bit more influence on being on the same page when it comes to auth and initialization. Exporting the underlying client would also be a valuable thing to consider if we are ok to expose the gRPC layer.

Thanks for all of the answers. I had little background. I have nothing against the motivation explained above. Closing the issue now.

**Comment by okdave** [comment]
Thanks @rakyll. I agree existing the underlying connection could be very valuable, but might need to wait until thing stabilise first.
