### ISSUE TITLE
datastore: way to represent no-retry condition for RunInTransaction

### ISSUE THREAD

**Issue by jmhodges** [GoogleCloudPlatform/gcloud-golang#329]
Per the Go docs on doing inserts (in constrate to upserts), the Go examples say to write code using `NewTransaction`

Which is totally fine! But the examples don't lay out all the Rollback work you need to do for the error conditions (this maybe should be a bug). 

it'd be nice to be able to use `RunInTransaction` to reduce that effort but you can't use `RunInTransaction` easily to do an insert, in general, because in many cases you'll want to return an error when there's already an entity at that key. But if you return an error, `RunInTransaction` will retry some number of times when you (as the developer) know that there's no way for it to succeed.

The workaround (smuggling a boolean into the closure representing if an entity existed already) is fine but a little ugly and action-at-a-distance-y. It would be maybe cool if there was some way to tell `RunInTransaction` to give up and not retry in some cases without the code looking too weird.

Maybe a special interface that the error returned to RunInTransaction that RunInTransaction could check for? Maybe with a helper to make simple ones a la `fmt.Errorf`?

I'd be willing to post that patch if folks are okay with that idea.

**Comment by okdave** [comment]
Thanks @jmhodges – I sent out a change for the related issue (#330) which changes to use `RunInTransaction` too.

As it turns out, there's no need for any extra special logic: `RunInTransaction` already only retries only on the error `ErrConcurrentTransaction`. So basically, if you return an error from your own function (and you don't manually make it that error – please don't do that!) then `RunInTransaction` will just give up.

The [documentation for RunInTransaction](https://godoc.org/cloud.google.com/go/datastore#Client.RunInTransaction) does actually call this out, though the func comment is quite long. It says it will retry if it "fails due to a conflicting transaction", but that if `f` returns a non-nil, it will rollback and give up.

**Comment by okdave** [comment]
Change is here: https://code-review.googlesource.com/7030
