### ISSUE TITLE
pubsub: Return a custom error if pull timeout occurs

### ISSUE THREAD

**Issue by rakyll** [GoogleCloudPlatform/gcloud-golang#67]

**Comment by mcgreevy** [comment]
This was fixed in e2fbd20 (ErrPullTimeout was removed).  

Notes:
- the underlying API no longer returns a 400 on timeout.
- the Pull and PullWait methods are deprecated in favour of Subscription.Pull.  The Iterator returned by Subscription.Pull will block until a message is available or the supplied context is cancelled.
